export const INSERT_TEXT_REQUEST = "INSERT_TEXT_REQUEST";
export const INSERT_TEXT_SUCCESS = "INSERT_TEXT_SUCCESS";
export const INSERT_TEXT_FAIL = "INSERT_TEXT_FAIL";

export const INSERT_IMAGE_REQUEST = "INSERT_IMAGE_REQUEST";
export const INSERT_IMAGE_SUCCESS = "INSERT_IMAGE_SUCCESS";
export const INSERT_IMAGE_FAIL = "INSERT_IMAGE_FAIL";

export const INSERT_VIDEO_REQUEST = "INSERT_VIDEO_REQUEST";
export const INSERT_VIDEO_SUCCESS = "INSERT_VIDEO_SUCCESS";
export const INSERT_VIDEO_FAIL = "INSERT_VIDEO_FAIL";

export const INSERT_LINK_REQUEST = "INSERT_LINK_REQUEST";
export const INSERT_LINK_SUCCESS = "INSERT_LINK_SUCCESS";
export const INSERT_LINK_FAIL = "INSERT_LINK_FAIL";

export const INSERT_DIVIDER_REQUEST = "INSERT_DIVIDER_REQUEST";
export const INSERT_DIVIDER_SUCCESS = "INSERT_DIVIDER_SUCCESS";
export const INSERT_DIVIDER_FAIL = "INSERT_DIVIDER_FAIL";

export const EDIT_TEXT_REQUEST = "EDIT_TEXT_REQUEST";
export const EDIT_TEXT_SUCCESS = "EDIT_TEXT_SUCCESS";
export const EDIT_TEXT_FAIL = "EDIT_TEXT_FAIL";

export const EDIT_CAPTION_REQUEST = "EDIT_CAPTION_REQUEST";
export const EDIT_CAPTION_SUCCESS = "EDIT_CAPTION_SUCCESS";
export const EDIT_CAPTION_FAIL = "EDIT_CAPTION_FAIL";

export const REMOVE_ELEMENT_REQUEST = "REMOVE_ELEMENT_REQUEST";
export const REMOVE_ELEMENT_SUCCESS = "REMOVE_ELEMENT_SUCCESS";
export const REMOVE_ELEMENT_FAIL = "REMOVE_ELEMENT_FAIL";
