export const EXERCISE_LIST_REQUEST = "EXERCISE_LIST_REQUEST";
export const EXERCISE_LIST_SUCCESS = "EXERCISE_LIST_SUCCESS";
export const EXERCISE_LIST_FAIL = "EXERCISE_LIST_FAIL";

export const ADD_EXERCISE_REQUEST = "ADD_EXERCISE_REQUEST";
export const ADD_EXERCISE_SUCCESS = "ADD_EXERCISE_SUCCESS";
export const ADD_EXERCISE_FAIL = "ADD_EXERCISE_FAIL";

export const EDIT_EXERCISE_TEXT_DATA_REQUEST =
  "EDIT_EXERCISE_TEXT_DATA_REQUEST";
export const EDIT_EXERCISE_TEXT_DATA_SUCCESS =
  "EDIT_EXERCISE_TEXT_DATA_SUCCESS";
export const EDIT_EXERCISE_TEXT_DATA_FAIL = "EDIT_EXERCISE_TEXT_DATA_FAIL";
