export const GOAL_LIST_REQUEST = "GOAL_LIST_REQUEST";
export const GOAL_LIST_SUCCESS = "GOAL_LIST_SUCCESS";
export const GOAL_LIST_FAIL = "GOAL_LIST_FAIL";

export const GET_ADD_GOAL_SCREEN_DATA_REQUEST =
  "GET_ADD_GOAL_SCREEN_DATA_REQUEST";
export const GET_ADD_GOAL_SCREEN_DATA_SUCCESS =
  "GET_ADD_GOAL_SCREEN_DATA_SUCCESS";
export const GET_ADD_GOAL_SCREEN_DATA_FAIL = "GET_ADD_GOAL_SCREEN_DATA_FAIL";

export const ADD_GOAL_REQUEST = "ADD_GOAL_REQUEST";
export const ADD_GOAL_SUCCESS = "ADD_GOAL_SUCCESS";
export const ADD_GOAL_FAIL = "ADD_GOAL_FAIL";

export const REMOVE_GOAL_REQUEST = "REMOVE_GOAL_REQUEST";
export const REMOVE_GOAL_SUCCESS = "REMOVE_GOAL_SUCCESS";
export const REMOVE_GOAL_FAIL = "REMOVE_GOAL_FAIL";

export const CHANGE_STATUS_REQUEST = "CHANGE_STATUS_REQUEST";
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
export const CHANGE_STATUS_FAIL = "CHANGE_STATUS_FAIL";

export const EDIT_PLAN_REQUEST = "EDIT_PLAN_REQUEST";
export const EDIT_PLAN_SUCCESS = "EDIT_PLAN_SUCCESS";
export const EDIT_PLAN_FAIL = "EDIT_PLAN_FAIL";
