export const NOTE_PAD_LIST_REQUEST = "NOTE_PAD_LIST_REQUEST";
export const NOTE_PAD_LIST_SUCCESS = "NOTE_PAD_LIST_SUCCESS";
export const NOTE_PAD_LIST_FAIL = "NOTE_PAD_LIST_FAIL";

export const NOTE_PAD_REQUEST = "NOTE_PAD_REQUEST";
export const NOTE_PAD_SUCCESS = "NOTE_PAD_SUCCESS";
export const NOTE_PAD_FAIL = "NOTE_PAD_FAIL";

export const ADD_NOTE_PAD_REQUEST = "ADD_NOTE_PAD_REQUEST";
export const ADD_NOTE_PAD_SUCCESS = "ADD_NOTE_PAD_SUCCESS";
export const ADD_NOTE_PAD_FAIL = "ADD_NOTE_PAD_FAIL";

export const ADD_TIMELINE_NOTE_PAD_REQUEST = "ADD_TIMELINE_NOTE_PAD_REQUEST";
export const ADD_TIMELINE_NOTE_PAD_SUCCESS = "ADD_TIMELINE_NOTE_PAD_SUCCESS";
export const ADD_TIMELINE_NOTE_PAD_FAIL = "ADD_TIMELINE_NOTE_PAD_FAIL";

export const UPDATE_NOTE_PAD_REQUEST = "UPDATE_NOTE_PAD_REQUEST";
export const UPDATE_NOTE_PAD_SUCCESS = "UPDATE_NOTE_PAD_SUCCESS";
export const UPDATE_NOTE_PAD_FAIL = "UPDATE_NOTE_PAD_FAIL";

export const EDIT_NOTEPAD_TITLE_REQUEST = "EDIT_NOTEPAD_TITLE_REQUEST";
export const EDIT_NOTEPAD_TITLE_SUCCESS = "EDIT_NOTEPAD_TITLE_SUCCESS";
export const EDIT_NOTEPAD_TITLE_FAIL = "EDIT_NOTEPAD_TITLE_FAIL";

export const REMOVE_NOTEPAD_REQUEST = "REMOVE_NOTE_PAD_REQUEST";
export const REMOVE_NOTEPAD_SUCCESS = "REMOVE_NOTE_PAD_SUCCESS";
export const REMOVE_NOTEPAD_FAIL = "REMOVE_NOTE_PAD_FAIL";
