export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL";

export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL";

export const REMOVE_PROJECT_REQUEST = "REMOVE_PROJECT_REQUEST";
export const REMOVE_PROJECT_SUCCESS = "REMOVE_PROJECT_SUCCESS";
export const REMOVE_PROJECT_FAIL = "REMOVE_PROJECT_FAIL";

export const GET_PROJECT_DATA_REQUEST = "GET_PROJECT_DATA_REQUEST";
export const GET_PROJECT_DATA_SUCCESS = "GET_PROJECT_DATA_SUCCESS";
export const GET_PROJECT_DATA_FAIL = "GET_PROJECT_DATA_FAIL";

export const EDIT_PROJECT_TITLE_REQUEST = "EDIT_PROJECT_TITLE_REQUEST";
export const EDIT_PROJECT_TITLE_SUCCESS = "EDIT_PROJECT_TITLE_SUCCESS";
export const EDIT_PROJECT_TITLE_FAIL = "EDIT_PROJECT_TITLE_FAIL";

export const EDIT_PROJECT_DESCRIPTION_REQUEST =
  "EDIT_PROJECT_DESCRIPTION_REQUEST";
export const EDIT_PROJECT_DESCRIPTION_SUCCESS =
  "EDIT_PROJECT_DESCRIPTION_SUCCESS";
export const EDIT_PROJECT_DESCRIPTION_FAIL = "EDIT_PROJECT_DESCRIPTION_FAIL";
