export const MONTHS_OF_QUARTER_REQUEST = "MONTHS_OF_QUARTER_REQUEST";
export const MONTHS_OF_QUARTER_SUCCESS = "MONTHS_OF_QUARTER_SUCCESS";
export const MONTHS_OF_QUARTER_FAIL = "MONTHS_OF_QUARTER_FAIL";
