export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";

export const COURSE_LIST_REQUEST = "COURSE_LIST_REQUEST";
export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";
export const COURSE_LIST_FAIL = "COURSE_LIST_FAIL";

export const ADD_RESOURCE_REQUEST = "ADD_RESOURCE_REQUEST";
export const ADD_RESOURCE_SUCCESS = "ADD_RESOURCE_SUCCESS";
export const ADD_RESOURCE_FAIL = "ADD_RESOURCE_FAIL";

export const REMOVE_RESOURCE_REQUEST = "REMOVE_RESOURCE_REQUEST";
export const REMOVE_RESOURCE_SUCCESS = "REMOVE_RESOURCE_SUCCESS";
export const REMOVE_RESOURCE_FAIL = "REMOVE_RESOURCE_FAIL";

export const GET_RESOURCE_DATA_REQUEST = "GET_RESOURCE_DATA_REQUEST";
export const GET_RESOURCE_DATA_SUCCESS = "GET_RESOURCE_DATA_SUCCESS";
export const GET_RESOURCE_DATA_FAIL = "GET_RESOURCE_DATA_FAIL";

export const EDIT_RESOURCE_TEXT_DATA_REQUEST =
  "EDIT_RESOURCE_TEXT_DATA_REQUEST";
export const EDIT_RESOURCE_TEXT_DATA_SUCCESS =
  "EDIT_RESOURCE_TEXT_DATA_SUCCESS";
export const EDIT_RESOURCE_TEXT_DATA_FAIL = "EDIT_RESOURCE_TEXT_DATA_FAIL";

export const EDIT_AUTHORS_REQUEST = "EDIT_AUTHORS_REQUEST";
export const EDIT_AUTHORS_SUCCESS = "EDIT_AUTHORS_SUCCESS";
export const EDIT_AUTHORS_FAIL = "EDIT_AUTHORS_FAIL";
