export const RESOLUTION_REQUEST = 'RESOLUTION_REQUEST'
export const RESOLUTION_SUCCESS = 'RESOLUTION_SUCCESS'
export const RESOLUTION_FAIL = 'RESOLUTION_FAIL'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'