export const ADD_SUBJECT_REQUEST = "ADD_SUBJECT_REQUEST ";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL";

export const LIST_SUBJECT_REQUEST = "LIST_SUBJECT_REQUEST ";
export const LIST_SUBJECT_SUCCESS = "LIST_SUBJECT_SUCCESS";
export const LIST_SUBJECT_FAIL = "LIST_SUBJECT_FAIL";

export const UPDATE_CURRENT_SUBJECT_REQUEST = "UPDATE_CURRENT_SUBJECT_REQUEST";
export const UPDATE_CURRENT_SUBJECT_SUCCESS = "UPDATE_CURRENT_SUBJECT_SUCCESS";
export const UPDATE_CURRENT_SUBJECT_FAIL = "UPDATE_CURRENT_SUBJECT_FAIL";
