export const GET_TRANSCRIPT_REQUEST = "GET_TRANSCRIPT_REQUEST";
export const GET_TRANSCRIPT_SUCCESS = "GET_TRANSCRIPT_SUCCESS";
export const GET_TRANSCRIPT_FAIL = "GET_TRANSCRIPT_FAIL";

export const EXPOSE_MATERIAL_REQUEST = "EXPOSE_MATERIAL_REQUEST";
export const EXPOSE_MATERIAL_SUCCESS = "EXPOSE_MATERIAL_SUCCESS";
export const EXPOSE_MATERIAL_FAIL = "EXPOSE_MATERIAL_FAIL";

export const HIDE_MATERIAL_REQUEST = "HIDE_MATERIAL_REQUEST";
export const HIDE_MATERIAL_SUCCESS = "HIDE_MATERIAL_SUCCESS";
export const HIDE_MATERIAL_FAIL = "HIDE_MATERIAL_FAIL";

export const REARRANGE_MATERIALS_REQUEST = "REARRANGE_MATERIALS_REQUEST";
export const REARRANGE_MATERIALS_SUCCESS = "REARRANGE_MATERIALS_SUCCESS";
export const REARRANGE_MATERIALS_FAIL = "REARRANGE_MATERIALS_FAIL";

export const GET_HIDDEN_MATERIALS_REQUEST = "GET_HIDDEN_MATERIALS_REQUEST";
export const GET_HIDDEN_MATERIALS_SUCCESS = "GET_HIDDEN_MATERIALS_SUCCESS";
export const GET_HIDDEN_MATERIALS_FAIL = "GET_HIDDEN_MATERIALS_FAIL";

export const MAKE_TRANSCRIPT_PRIVATE_REQUEST =
  "MAKE_TRANSCRIPT_PRIVATE_REQUEST";
export const MAKE_TRANSCRIPT_PRIVATE_SUCCESS =
  "MAKE_TRANSCRIPT_PRIVATE_SUCCESS";
export const MAKE_TRANSCRIPT_PRIVATE_FAIL = "MAKE_TRANSCRIPT_PRIVATE_FAIL";

export const MAKE_TRANSCRIPT_PUBLIC_REQUEST = "MAKE_TRANSCRIPT_PUBLIC_REQUEST";
export const MAKE_TRANSCRIPT_PUBLIC_SUCCESS = "MAKE_TRANSCRIPT_PUBLIC_SUCCESS";
export const MAKE_TRANSCRIPT_PUBLIC_FAIL = "MAKE_TRANSCRIPT_PUBLIC_FAIL";

export const GET_PUBLIC_TRANSCRIPT_REQUEST = "GET_PUBLIC_TRANSCRIPT_REQUEST";
export const GET_PUBLIC_TRANSCRIPT_SUCCESS = "GET_PUBLIC_TRANSCRIPT_SUCCESS";
export const GET_PUBLIC_TRANSCRIPT_FAIL = "GET_PUBLIC_TRANSCRIPT_FAIL";
