export const GET_REMOVED_ITEMS_REQUEST = "GET_REMOVED_ITEMS_REQUEST";
export const GET_REMOVED_ITEMS_SUCCESS = "GET_REMOVED_ITEMS_SUCCESS";
export const GET_REMOVED_ITEMS_FAIL = "GET_REMOVED_ITEMS_FAIL";

export const RESTORE_ITEM_REQUEST = "RESTORE_ITEM_REQUEST";
export const RESTORE_ITEM_SUCCESS = "RESTORE_ITEM_SUCCESS";
export const RESTORE_ITEM_FAIL = "RESTORE_ITEM_FAIL";

export const PERMANENTLY_DELETE_ITEM_REQUEST =
  "PERMANENTLY_DELETE_ITEM_REQUEST";
export const PERMANENTLY_DELETE_ITEM_SUCCESS =
  "PERMANENTLY_DELETE_ITEM_SUCCESS";
export const PERMANENTLY_DELETE_ITEM_FAIL = "PERMANENTLY_DELETE_ITEM_FAIL";
