export const WEEK_LIST_REQUEST = "WEEK_LIST_REQUEST";
export const WEEK_LIST_SUCCESS = "WEEK_LIST_SUCCESS";
export const WEEK_LIST_FAIL = "WEEK_LIST_FAIL";

export const DAYS_OF_WEEK_REQUEST = "DAYS_OF_WEEK_REQUEST";
export const DAYS_OF_WEEK_SUCCESS = "DAYS_OF_WEEK_SUCCESS";
export const DAYS_OF_WEEK_FAIL = "DAYS_OF_WEEK_FAIL";
