export const YEAR_LIST_REQUEST = "YEAR_LIST_REQUEST";
export const YEAR_LIST_SUCCESS = "YEAR_LIST_SUCCESS";
export const YEAR_LIST_FAIL = "YEAR_LIST_FAIL";

export const ADD_YEAR_REQUEST = "ADD_YEAR_REQUEST";
export const ADD_YEAR_SUCCESS = "ADD_YEAR_SUCCESS";
export const ADD_YEAR_FAIL = "ADD_YEAR_FAIL";

export const LIST_YEARS_WITH_QUARTERS_REQUEST =
  "LIST_YEARS_WITH_QUARTERS_REQUEST";
export const LIST_YEARS_WITH_QUARTERS_SUCCESS =
  "LIST_YEARS_WITH_QUARTERS_SUCCESS";
export const LIST_YEARS_WITH_QUARTERS_FAIL = "LIST_YEARS_WITH_QUARTERS_FAIL";
